"""SQLAlchemy ORM models for PostGIS-backed spatial tables.

Two tables are provided:

* ``spatial_points_2d`` – stores 2-D points as ``geometry(POINT, 0)``
  (SRID 0 = unitless abstract coordinate space). Intended for flat QR-module
  grid use-cases where only *x* and *y* matter.

* ``spatial_points_3d`` – stores 3-D points as ``geometry(POINTZ, 0)``.
  Intended for :class:`~computational_qr.graphs.graph_3d.Graph3D` and
  :class:`~computational_qr.core.color_geometry.ColorGeometry` use-cases where
  *x*, *y*, *z* are all meaningful.

Both tables are only defined when **GeoAlchemy2** is installed
(``pip install 'computational-qr[postgis]'``).  The ``POSTGIS_AVAILABLE`` flag
can be tested at runtime to guard PostGIS-specific code paths::

    from computational_qr.database.spatial_models import POSTGIS_AVAILABLE

    if POSTGIS_AVAILABLE:
        from computational_qr.database.spatial_models import SpatialPoint3D
"""

from __future__ import annotations

import uuid as _uuid

try:
    from geoalchemy2 import Geometry  # type: ignore[import-untyped]

    POSTGIS_AVAILABLE = True
except ImportError:
    POSTGIS_AVAILABLE = False
    Geometry = None  # type: ignore[assignment,misc]

from sqlalchemy import Float, Index, Integer, String
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import mapped_column, Mapped

from computational_qr.database.relational_store import Base


if POSTGIS_AVAILABLE:

    class SpatialPoint2D(Base):
        """Row in ``spatial_points_2d``.

        Parameters
        ----------
        id:
            UUID primary key (generated by Python if not provided).
        scene_id:
            Groups points belonging to the same computation scene.
        label:
            Human-readable identifier for the point.
        dimension:
            Data dimension index (mirrors the concept in
            :class:`~computational_qr.graphs.graph_3d.DataPoint`).
        value:
            Scalar magnitude of the data point.
        metadata:
            Arbitrary JSON annotations.
        geom:
            2-D PostGIS geometry ``POINT`` with SRID 0.
        """

        __tablename__ = "spatial_points_2d"
        __table_args__ = (
            Index(
                "idx_spatial_points_2d_geom",
                "geom",
                postgresql_using="gist",
            ),
        )

        id: Mapped[_uuid.UUID] = mapped_column(
            PG_UUID(as_uuid=True),
            primary_key=True,
            default=_uuid.uuid4,
        )
        scene_id: Mapped[_uuid.UUID] = mapped_column(
            PG_UUID(as_uuid=True),
            nullable=False,
            index=True,
        )
        label: Mapped[str] = mapped_column(String, nullable=False)
        dimension: Mapped[int | None] = mapped_column(Integer, nullable=True, index=True)
        value: Mapped[float | None] = mapped_column(Float, nullable=True)
        metadata_: Mapped[dict | None] = mapped_column(
            "metadata", JSONB, nullable=True
        )
        geom = mapped_column(Geometry("POINT", srid=0), nullable=False)

    class SpatialPoint3D(Base):
        """Row in ``spatial_points_3d``.

        Parameters
        ----------
        id:
            UUID primary key (generated by Python if not provided).
        scene_id:
            Groups points belonging to the same computation scene.
        label:
            Human-readable identifier for the point.
        dimension:
            Data dimension index.
        value:
            Scalar magnitude of the data point.
        metadata:
            Arbitrary JSON annotations.
        geom:
            3-D PostGIS geometry ``POINTZ`` with SRID 0.
        """

        __tablename__ = "spatial_points_3d"
        __table_args__ = (
            Index(
                "idx_spatial_points_3d_geom",
                "geom",
                postgresql_using="gist",
            ),
        )

        id: Mapped[_uuid.UUID] = mapped_column(
            PG_UUID(as_uuid=True),
            primary_key=True,
            default=_uuid.uuid4,
        )
        scene_id: Mapped[_uuid.UUID] = mapped_column(
            PG_UUID(as_uuid=True),
            nullable=False,
            index=True,
        )
        label: Mapped[str] = mapped_column(String, nullable=False)
        dimension: Mapped[int | None] = mapped_column(Integer, nullable=True, index=True)
        value: Mapped[float | None] = mapped_column(Float, nullable=True)
        metadata_: Mapped[dict | None] = mapped_column(
            "metadata", JSONB, nullable=True
        )
        geom = mapped_column(Geometry("POINTZ", srid=0), nullable=False)

else:
    # Placeholders so the names can be imported unconditionally.
    SpatialPoint2D = None  # type: ignore[assignment,misc]
    SpatialPoint3D = None  # type: ignore[assignment,misc]


__all__ = [
    "POSTGIS_AVAILABLE",
    "SpatialPoint2D",
    "SpatialPoint3D",
]
